import { StyleSheet } from 'react-native'

export default StyleSheet.create({
    // =============================================================================
    wrapper: {
    },
    slide1: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#9DD6EB',
    },
    slide2: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#97CAE5',
    },
    slide3: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#92BBD9',
    },
    slide4: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#ffffff',
    },
    slide5: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'red',
    },
    slide6: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'red',
    },
    slide7: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'red',
    },
    slide8: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'red',
    },
    slide9: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'red',
    },
    text: {
        color: '#fff',
        fontSize: 30,
        fontWeight: 'bold',
    },

    // STYLES TUTORIAL 1 ======================================================================
    homeImageArea: {
        flexDirection: "column",
        flex: 3.6,
        backgroundColor: "#ffffff",
        width: "100%",
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    homeTextArea: {
        flexDirection: "column",
        flex: 1.85,
        paddingTop: 0,
        paddingLeft: 50,
        paddingRight: 50,
        backgroundColor: '#ffffff',
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    TextArea1: {
        color: '#020202',
        fontSize: 25,
        marginBottom: 22,
        fontWeight: "bold",
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    TextArea2: {
        color: '#020202',
        fontSize: 18,
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    homeButtonArea: {
        flexDirection: "column",
        flex: 0.55,
        width: "100%",
        alignItems: 'stretch',
        backgroundColor: "#ffffff"
    },
    button: {
        width: '100%',
        height: '100%',
        backgroundColor: "#c62825",
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center'
    },
    buttonTitle: {
        fontFamily: 'IBM Plex Sans',
        color: '#ffffff'
    },

    // STYLES TUTORIAL 2 ======================================================================
    homeTopBarArea2: {
        flexDirection: "column",
        flex: 0.6,
        paddingLeft: 22,
        backgroundColor: "#ffffff",
        width: "100%",
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    homeImageArea2: {
        flexDirection: "column",
        flex: 3,
        backgroundColor: "#ffffff",
        width: "100%",
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    homeTextArea22: {
        flexDirection: "column",
        flex: 1.85,
        paddingTop: 0,
        paddingLeft: 50,
        paddingRight: 50,
        backgroundColor: '#ffffff',
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    TextArea12: {
        color: '#020202',
        fontSize: 25,
        marginBottom: 22,
        fontWeight: "bold",
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    TextArea22: {
        color: '#020202',
        fontSize: 18,
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    homebutton2Area2: {
        flexDirection: "column",
        flex: 0.55,
        width: "100%",
        alignItems: 'stretch',
        backgroundColor: "#ffffff"
    },
    button2: {
        width: '100%',
        height: '100%',
        backgroundColor: "#c62825",
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center'
    },
    button2Title2: {
        fontFamily: 'IBM Plex Sans',
        color: '#ffffff'
    },

    // STYLES TUTORIAL 3 ======================================================================
    homeTopBarArea3: {
        flexDirection: "row",
        // flex: 0.6,
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 22,
        paddingRight: 22,
        backgroundColor: "#ffffff",
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    homeTopBarAreaBack3: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'blue',
        width: 32,
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    homeTopBarAreaClose3: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'red',
        width: 32,
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
    },
    homeImageArea3: {
        flexDirection: "column",
        flex: 3.35,
        backgroundColor: "#ffffff",
        width: "100%",
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    homeTextArea3: {
        flexDirection: "column",
        flex: 1.8,
        paddingTop: 0,
        paddingLeft: 40,
        paddingRight: 40,
        backgroundColor: '#ffffff',
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    TextArea13: {
        color: '#020202',
        fontSize: 25,
        marginLeft: 50,
        marginRight: 50,
        marginBottom: 40,
        fontWeight: "bold",
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    TextArea23: {
        color: '#020202',
        fontSize: 18,
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    homebuttonArea33: {
        flexDirection: "column",
        flex: 0.55,
        width: "100%",
        alignItems: 'stretch',
        backgroundColor: "#ffffff"
    },
    button3: {
        width: '100%',
        height: '100%',
        backgroundColor: "#c62825",
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center'
    },
    buttonTitle3: {
        fontFamily: 'IBM Plex Sans',
        color: '#ffffff'
    },

    // STYLES TUTORIAL 4 ======================================================================
    homeTopBarArea4: {
        flexDirection: "row",
        // flex: 0.6,
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 22,
        paddingRight: 22,
        backgroundColor: "#ffffff",
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    homeTopBarAreaBack4: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'blue',
        width: 32,
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    homeTopBarAreaClose4: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'red',
        width: 32,
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
    },
    homeImageArea4: {
        flexDirection: "column",
        flex: 3.35,
        backgroundColor: "#ffffff",
        width: "100%",
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    homeTextArea4: {
        flexDirection: "column",
        flex: 1.8,
        paddingTop: 0,
        paddingLeft: 40,
        paddingRight: 40,
        backgroundColor: '#ffffff',
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    TextArea14: {
        color: '#020202',
        fontSize: 25,
        marginLeft: 50,
        marginRight: 50,
        marginBottom: 40,
        fontWeight: "bold",
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    TextArea24: {
        color: '#020202',
        fontSize: 18,
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    homebuttonArea4: {
        flexDirection: "column",
        flex: 0.55,
        width: "100%",
        alignItems: 'stretch',
        backgroundColor: "#ffffff"
    },
    button4: {
        width: '100%',
        height: '100%',
        backgroundColor: "#c62825",
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center'
    },
    buttonTitle4: {
        fontFamily: 'IBM Plex Sans',
        color: '#ffffff'
    },

    // STYLES TUTORIAL 5 ======================================================================
    homeTopBarArea5: {
        flexDirection: "row",
        // flex: 0.6,
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 22,
        paddingRight: 22,
        backgroundColor: "#ffffff",
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    homeTopBarAreaBack5: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'blue',
        width: 32,
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    homeTopBarAreaClose5: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'red',
        width: 32,
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
    },
    homeImageArea5: {
        flexDirection: "column",
        flex: 3.35,
        backgroundColor: "#ffffff",
        width: "100%",
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    homeTextArea5: {
        flexDirection: "column",
        flex: 1.8,
        paddingTop: 0,
        paddingLeft: 40,
        paddingRight: 40,
        backgroundColor: '#ffffff',
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    TextArea15: {
        color: '#020202',
        fontSize: 25,
        marginLeft: 50,
        marginRight: 50,
        marginBottom: 40,
        fontWeight: "bold",
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    TextArea25: {
        color: '#020202',
        fontSize: 18,
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    homebutton5Area5: {
        flexDirection: "column",
        flex: 0.55,
        width: "100%",
        alignItems: 'stretch',
        backgroundColor: "#ffffff"
    },
    button5: {
        width: '100%',
        height: '100%',
        backgroundColor: "#c62825",
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center'
    },
    buttonTitle5: {
        fontFamily: 'IBM Plex Sans',
        color: '#ffffff'
    },

    // STYLES TUTORIAL 6 ======================================================================
    homeTopBarArea6: {
        flexDirection: "row",
        // flex: 0.6,
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 22,
        paddingRight: 22,
        backgroundColor: "#ffffff",
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    homeTopBarAreaBack6: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'blue',
        width: 32,
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    homeTopBarAreaClose6: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'red',
        width: 32,
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
    },
    homeImageArea6: {
        flexDirection: "column",
        flex: 3.35,
        backgroundColor: "#ffffff",
        width: "100%",
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    homeTextArea6: {
        flexDirection: "column",
        flex: 1.8,
        paddingTop: 0,
        paddingLeft: 40,
        paddingRight: 40,
        backgroundColor: '#ffffff',
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    TextArea16: {
        color: '#020202',
        fontSize: 25,
        marginLeft: 50,
        marginRight: 50,
        marginBottom: 40,
        fontWeight: "bold",
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    TextArea26: {
        color: '#020202',
        fontSize: 18,
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    homebutton6Area6: {
        flexDirection: "column",
        flex: 0.55,
        width: "100%",
        alignItems: 'stretch',
        backgroundColor: "#ffffff"
    },
    button6: {
        width: '100%',
        height: '100%',
        backgroundColor: "#c62825",
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center'
    },
    buttonTitle6: {
        fontFamily: 'IBM Plex Sans',
        color: '#ffffff'
    },

    // STYLES TUTORIAL 7 ======================================================================
    homeTopBarArea7: {
        flexDirection: "row",
        // flex: 0.6,
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 22,
        paddingRight: 22,
        backgroundColor: "#ffffff",
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    homeTopBarAreaBack7: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'blue',
        width: 32,
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    homeTopBarAreaClose7: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'red',
        width: 32,
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
    },
    homeImageArea7: {
        flexDirection: "column",
        flex: 3.35,
        backgroundColor: "#ffffff",
        width: "100%",
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    homeTextArea7: {
        flexDirection: "column",
        flex: 1.8,
        paddingTop: 0,
        paddingLeft: 40,
        paddingRight: 40,
        backgroundColor: '#ffffff',
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    TextArea17: {
        color: '#020202',
        fontSize: 25,
        marginLeft: 50,
        marginRight: 50,
        marginBottom: 40,
        fontWeight: "bold",
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    TextArea27: {
        color: '#020202',
        fontSize: 18,
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    homebutton7Area7: {
        flexDirection: "column",
        flex: 0.55,
        width: "100%",
        alignItems: 'stretch',
        backgroundColor: "#ffffff"
    },
    button7: {
        width: '100%',
        height: '100%',
        backgroundColor: "#c62825",
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center'
    },
    buttonTitle7: {
        fontFamily: 'IBM Plex Sans',
        color: '#ffffff'
    },

    // STYLES TUTORIAL 8 ======================================================================
    homeTopBarArea8: {
        flexDirection: "row",
        // flex: 0.6,
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 22,
        paddingRight: 22,
        backgroundColor: "#ffffff",
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    homeTopBarAreaBack8: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'blue',
        width: 32,
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    homeTopBarAreaClose8: {
        flexDirection: 'row',
        flex: 3,
        // backgroundColor: 'red',
        width: 32,
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
    },
    homeImageArea8: {
        flexDirection: "column",
        flex: 3.35,
        backgroundColor: "#ffffff",
        width: "100%",
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    homeTextArea8: {
        flexDirection: "column",
        flex: 1.8,
        paddingTop: 0,
        paddingLeft: 40,
        paddingRight: 40,
        backgroundColor: '#ffffff',
        width: "100%",
        alignItems: 'center',
        // justifyContent: 'center',
    },
    TextArea18: {
        color: '#020202',
        fontSize: 25,
        marginLeft: 50,
        marginRight: 50,
        marginBottom: 40,
        fontWeight: "bold",
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    TextArea28: {
        color: '#020202',
        fontSize: 18,
        fontFamily: 'IBM Plex Sans',
        textAlign: 'center',
    },
    homebutton8Area8: {
        flexDirection: "column",
        flex: 0.55,
        width: "100%",
        alignItems: 'stretch',
        backgroundColor: "#ffffff"
    },
    button8: {
        width: '100%',
        height: '100%',
        backgroundColor: "#c62825",
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center'
    },
    buttonTitle8: {
        fontFamily: 'IBM Plex Sans',
        color: '#ffffff'
    }
})  